import "./globals.css";
import { StoryblokProvider } from "@/lib/providers/storyblokProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
      <html lang="en" className="h-full">
        <body className="h-full">
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}